[book]
title    = "XQVM Documentation"
authors  = [ "Postquant Labs Incorporated" ]
language = "en"
src      = "docs/book/src"

[build]
build-dir      = "docs/book/build"
create-missing = false

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://gitlab.com/quip.network/xquad"
edit-url-template  = "https://gitlab.com/quip.network/xquad/-/edit/main/{path}"
mathjax-support    = true
additional-js      = [ "mermaid.min.js", "mermaid-init.js" ]
