// Copyright (C) 2026 Postquant Labs Incorporated
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Build-time parity: reads `xqvm/opcodes.yaml` and emits a const
//! opcode table that the crate compares against the `opcodes!` x-macro in
//! `src/bytecode/types/parity.rs`. Any mismatch becomes a compile error.
//!
//! The emitted table carries the wire byte, the mnemonic, the stack effect
//! and the operand layout as `(name, byte width)` pairs. The stack effect
//! is the YAML's `stack_pop`/`stack_push` pair spelled as the same
//! `StackEffect` the x-macro stores, or `StackEffect::Reset` for an opcode
//! with `stack_reset`, so pops and pushes are compared separately.
//!
//! Build scripts run at compile time with no caller to propagate errors
//! to, so panicking on failure is the correct behaviour. The workspace's
//! `clippy::panic` and `clippy::expect_used` lints are allowed here for
//! that reason.

#![expect(
    clippy::expect_used,
    clippy::panic,
    reason = "build scripts halt the compilation on failure; panics are the idiomatic exit path"
)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(serde::Deserialize)]
struct Root {
    opcodes: Vec<Op>,
}

#[derive(serde::Deserialize)]
struct Op {
    code: u8,
    mnemonic: String,
    #[serde(default)]
    operands: Vec<Operand>,
    stack_pop: u8,
    stack_push: u8,
    /// True for an opcode that empties the stack outright rather than
    /// popping and pushing a fixed count. `SCLR` alone; it is
    /// `StackEffect::Reset` in `src/bytecode/types/table.rs`.
    #[serde(default)]
    stack_reset: bool,
}

#[derive(serde::Deserialize)]
struct Operand {
    name: String,
    #[serde(default = "default_operand_width")]
    width: u8,
}

const fn default_operand_width() -> u8 {
    1
}

/// Spell the YAML's `stack_pop`/`stack_push`/`stack_reset` triple as the
/// `StackEffect` expression the `opcodes!` x-macro carries for that row.
fn stack_effect(op: &Op) -> String {
    if op.stack_reset {
        assert!(
            op.stack_pop == 0 && op.stack_push == 0,
            "opcode {} ({:#04X}): stack_reset is true, so stack_pop and stack_push must both \
             be 0 -- a reset has no fixed count to declare",
            op.mnemonic,
            op.code
        );
        return "StackEffect::Reset".to_owned();
    }
    format!("StackEffect::fixed({}, {})", op.stack_pop, op.stack_push)
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR must be set by cargo"),
    );

    // The table ships inside the crate, so the workspace build and the
    // packaged build read the same file.
    let yaml_path = manifest_dir.join("opcodes.yaml");

    println!("cargo:rerun-if-changed={}", yaml_path.display());

    let raw = fs::read_to_string(&yaml_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", yaml_path.display()));
    let parsed: Root = serde_yaml_ng::from_str(&raw)
        .unwrap_or_else(|e| panic!("failed to parse {}: {e}", yaml_path.display()));

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR must be set by cargo");
    let dest = Path::new(&out_dir).join("opcodes_yaml.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from xqvm/opcodes.yaml.\n");
    code.push_str(
        "// Do not edit; regenerate by touching opcodes.yaml and re-running `cargo build`.\n\n",
    );
    // Each row is (code, mnemonic, stack effect, operands), where an
    // operand is (name, byte width). `OpcodeRow` is the alias parity.rs
    // declares for that tuple; the shape mirrors what parity.rs derives
    // from the `opcodes!` x-macro so the comparison there stays a
    // field-by-field equality.
    code.push_str("const YAML_OPCODES: &[OpcodeRow] = &[\n");
    for op in &parsed.opcodes {
        let effect = stack_effect(op);
        let mut operands = String::new();
        for operand in &op.operands {
            assert!(
                operand.width != 0,
                "opcode {} ({:#04X}): operand `{}` has width 0",
                op.mnemonic,
                op.code,
                operand.name
            );
            write!(operands, "(\"{}\", {}), ", operand.name, operand.width)
                .expect("writing to a String cannot fail");
        }
        writeln!(
            code,
            "    ({:#04X}, \"{}\", {effect}, &[{}]),",
            op.code,
            op.mnemonic,
            operands.trim_end_matches(", ")
        )
        .expect("writing to a String cannot fail");
    }
    code.push_str("];\n");

    fs::write(&dest, code).unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}
