#!/usr/bin/env bash
# Copyright (C) 2026 Postquant Labs Incorporated
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Commit message guard.
#
# .githooks/commit-msg already enforces Conventional Commits and DCO
# sign-off, but it is opt-in (make install-hooks) and bypassable
# (git commit --no-verify), so it can never be the actual gate. This
# script re-runs the same grammar (scripts/commit-grammar.sh, shared
# with the hook so the two rule sets cannot drift) over every commit
# in a merge request's range, for a CI job to call.
#
# Merge commits are skipped: they are server-generated by GitLab, not
# authored, and "merge" is deliberately not a Conventional Commits
# type. See scripts/commit-grammar.sh's MERGE_SUBJECT_PATTERN.
#
# Usage:
#   scripts/check-commit-messages.sh [BASE_REF] [HEAD_REF]
#
# Defaults (mirrors scripts/check-atomic-spec-mr.sh):
#   - In GitLab CI: BASE_REF = $CI_MERGE_REQUEST_DIFF_BASE_SHA,
#     HEAD_REF = HEAD.
#   - Locally: BASE_REF = $(git merge-base origin/main HEAD),
#     HEAD_REF = HEAD.
#
# Exit codes:
#   0  -- every non-merge commit in the range passes
#   1  -- at least one commit fails the grammar
#   2  -- usage / setup error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=commit-grammar.sh
source "${SCRIPT_DIR}/commit-grammar.sh"

# --- Argument / environment resolution -------------------------------------

BASE_REF="${1:-}"
if [[ -z "${BASE_REF}" ]]; then
    BASE_REF="${CI_MERGE_REQUEST_DIFF_BASE_SHA:-}"
fi
if [[ -z "${BASE_REF}" ]]; then
    if ! BASE_REF="$(git merge-base origin/main HEAD 2>/dev/null)"; then
        echo "error: could not derive BASE_REF (no arg, no CI var, no origin/main)" >&2
        exit 2
    fi
fi

HEAD_REF="${2:-HEAD}"

if ! git rev-parse --verify "${BASE_REF}" >/dev/null 2>&1; then
    echo "error: base ref '${BASE_REF}' does not resolve" >&2
    exit 2
fi
if ! git rev-parse --verify "${HEAD_REF}" >/dev/null 2>&1; then
    echo "error: head ref '${HEAD_REF}' does not resolve" >&2
    exit 2
fi

# --- Walk the range and validate each commit --------------------------------

commits="$(git rev-list --reverse "${BASE_REF}..${HEAD_REF}")"

if [[ -z "${commits}" ]]; then
    echo "guard: no commits in ${BASE_REF}..${HEAD_REF}"
    exit 0
fi

checked=0
skipped=0
failed=0

while IFS= read -r sha; do
    [[ -z "${sha}" ]] && continue

    message="$(git log -1 --format=%B "${sha}")"
    subject="$(commit_subject <<< "${message}")"
    short="$(git rev-parse --short "${sha}")"

    if [[ -z "${subject}" ]]; then
        echo "FAIL ${short}: empty commit message" >&2
        failed=$((failed + 1))
        continue
    fi

    if is_merge_subject "${subject}"; then
        echo "skip ${short}: merge commit (${subject})"
        skipped=$((skipped + 1))
        continue
    fi

    checked=$((checked + 1))
    commit_ok=1

    if ! check_commit_subject "${subject}" 2> >(sed "s/^/  ${short}: /" >&2); then
        commit_ok=0
    fi
    if ! check_signed_off <<< "${message}" 2> >(sed "s/^/  ${short}: /" >&2); then
        commit_ok=0
    fi

    if [[ "${commit_ok}" -eq 1 ]]; then
        echo "pass ${short}: ${subject}"
    else
        echo "FAIL ${short}: ${subject}" >&2
        failed=$((failed + 1))
    fi
done <<< "${commits}"

echo ""
echo "guard: ${checked} checked, ${skipped} merge commit(s) skipped, ${failed} failed"

if [[ "${failed}" -gt 0 ]]; then
    exit 1
fi

exit 0
