#!/usr/bin/env bash
# Copyright (C) 2026 Postquant Labs Incorporated
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Commit message guard.
#
# .githooks/commit-msg already enforces Conventional Commits and DCO
# sign-off, but it is opt-in (make install-hooks) and bypassable
# (git commit --no-verify), so it can never be the actual gate. This
# script re-runs the same grammar (scripts/commit-grammar.sh, shared
# with the hook so the two rule sets cannot drift) over every commit
# in a merge request's range, for a CI job to call.
#
# Merge commits are skipped: they are server-generated by GitLab, not
# authored, and "merge" is deliberately not a Conventional Commits
# type. See scripts/commit-grammar.sh's MERGE_SUBJECT_PATTERN.
#
# Usage:
#   scripts/check-commit-messages.sh [BASE_REF] [HEAD_REF]
#
# Defaults (mirrors scripts/check-atomic-spec-mr.sh):
#   - In GitLab CI: BASE_REF = $CI_MERGE_REQUEST_DIFF_BASE_SHA,
#     HEAD_REF = $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA, then HEAD.
#   - Locally: BASE_REF = $(git merge-base origin/main HEAD),
#     HEAD_REF = HEAD.
#
# When that merge-base default produces an empty range on main, the
# script checks what the last push landed there instead of exiting.
# See "Landed mode" below.
#
# HEAD is the wrong head ref in a merged-result pipeline. There $HEAD
# is the source merged into the target, so BASE_REF..HEAD holds the
# branch's own commits plus every commit the target accumulated since
# the branch was cut. Those extra commits are already on main and the
# merge request does not own them: it cannot edit a message on its
# target, so the only response to a finding there is a rebase, which
# has nothing to do with the rule being checked. They carry no
# true-positive case, only the risk of one.
#
# The risk is not hypothetical. Every commit before e271004 -- the
# commit that added this guard -- is unsigned, so a branch cut before
# it fails on roughly 54 commits its author cannot fix. Rebasing
# clears that today, but two things reopen it on branches that are
# already current: tightening the shared grammar (a required ticket
# footer, a shorter subject limit) turns commits that already passed
# on main into violations, and a maintainer pushing straight to main
# -- branch protection allows it -- puts one unchecked commit in every
# open branch's range at once.
#
# $CI_MERGE_REQUEST_SOURCE_BRANCH_SHA is the un-squashed branch tip,
# which cuts the range to exactly the commits the merge request
# authored.
#
# Landed mode -- an empty merge-base range on a long-lived branch is
# where whatever a push landed finally gets checked.
#
# It was written for a premise that no longer holds. Until QUI-1256,
# squash_option was `always` and squash_commit_template was %{title}, so
# every merge put the merge request title on main as an authored commit
# subject; GitLab starts pipelines on push and not on title edits, so a
# title edited after the last pipeline reached main unchecked. The
# project now merges unsquashed. Every commit a merge request lands was
# already inside the range that merge request's own pipeline checked,
# and the title is no longer a commit subject at all.
#
# The mode keeps a job, and it is a different one. `main` is closed to
# direct pushes; `dev` is not -- it stays pushable by Maintainers so a
# back-merge is a single push (docs/guide/gitflow-protocol.md). A direct
# push is the one path no merge-request-range guard sees:
# scripts/check-mr-title.sh is merge-request-only by nature and
# scripts/check-atomic-spec-mr.sh diffs a merge request range. So landed
# mode watches `dev` for what is pushed straight to it, and keeps
# watching `main` for a push that branch protection is not supposed to
# permit but that a settings change could re-permit without anyone
# touching this file.
#
# Either way, a subject that fails the grammar is dropped from the
# release notes by cliff.toml's `filter_unconventional` without a word.
# Silent is the part worth fixing; the entry is simply missing from a
# version's notes and nothing anywhere says why.
#
# On a long-lived branch's own pipeline BASE_REF falls through to
# `git merge-base origin/<that branch> HEAD`, which resolves to HEAD,
# so the range is empty and this guard would exit 0 having read
# nothing. That empty range is the trigger, subject to two conditions.
#
# The upstream is the branch's own remote ref, not origin/main, for
# exactly that reason. Measured against origin/main the range on a
# `dev` pipeline is every commit dev carries that main does not --
# dozens of them, each already checked by the merge request that
# landed it, and growing until the next back-merge. Emptiness has to
# mean "this push is all that is new here", which only the branch's
# own upstream can say.
#
# First, the range has to be one this script guessed at. An explicit
# BASE/HEAD argument and $CI_MERGE_REQUEST_DIFF_BASE_SHA each name a
# range somebody asked about, and an empty one is an answer rather
# than a cue to go looking elsewhere. That is also what keeps merge
# request pipelines out of landed mode, where the tip is a commit the
# merge request does not own.
#
# Second, the ref has to be one of the long-lived branches. Emptiness
# alone does not say the run is looking at one of them after a merge:
# a branch cut from main and pushed before it has any commits of its
# own is the same commit as main, so `merge-base(origin/main, HEAD)`
# is HEAD there too. Its branch pipeline -- .gitlab-ci.yml starts one
# for any branch with no open merge request -- and a local
# `make preflight-policy` would otherwise both go red over main's
# history, the exact failure the paragraphs above exist to prevent.
# Nothing about the commit separates the two cases; only the ref does,
# which is what REF_NAME is for. Tag pipelines are excluded by the
# same test and lose nothing: release:auto-tag tags a commit whose
# main pipeline already checked it.
#
# What gets checked is the push, not the tip. $CI_COMMIT_BEFORE_SHA is
# the tip main had before the push, so $CI_COMMIT_BEFORE_SHA..HEAD is
# exactly what the push introduced: the merge commit plus its squash
# commit for a merge, or every commit of a direct push -- branch
# protection allows those, and taking only the tip would check one
# subject out of however many landed. Off CI nothing records what the
# last pull brought in, so the fallback is the tip's non-first parents
# (with squash-on-merge, the one squash commit carrying the title) or
# the tip itself when it has none. That fallback under-reports a
# multi-commit pull, which is tolerable for a local preview of what
# the main pipeline will say and intolerable for the pipeline itself.
#
# The push range does not reopen the objection to HEAD^1..HEAD, which
# would pull in the whole branch side and re-run the grammar over
# history nobody can fix any more. A commit reachable from an older
# main is reachable from $CI_COMMIT_BEFORE_SHA and so is excluded by
# construction; the range holds only commits new to main. For a
# merge-commit merge the branch's own commits are in it, and those are
# the commits that merge request's own pipeline already checked.
#
# Detection, not prevention: the commit is on main by the time this
# runs. scripts/check-mr-title.sh is still the check that stops a bad
# title from landing; this one stops it from landing quietly.
#
# Exit codes:
#   0  -- every non-merge commit in the range passes
#   1  -- at least one commit fails the grammar
#   2  -- usage / setup error

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=commit-grammar.sh
source "${SCRIPT_DIR}/commit-grammar.sh"

# --- Argument / environment resolution -------------------------------------

# The long-lived branches, in one place: landed mode watches these and
# nothing else, and a run on one measures its range against that
# branch's own upstream rather than against main.
LANDED_REFS=("main" "dev")

is_landed_ref() {
    local candidate="$1" ref
    for ref in "${LANDED_REFS[@]}"; do
        [[ "${candidate}" == "${ref}" ]] && return 0
    done
    return 1
}

# Which ref this run is checking, as opposed to which commit. HEAD_REF
# cannot answer that: a branch cut from main and pushed before it has
# commits of its own is the same commit as main, and only the ref name
# tells the two apart. Landed mode below turns on it, and the failure
# message names it.
#
# $CI_COMMIT_BRANCH comes first because GitLab checks out a detached
# HEAD, where symbolic-ref finds nothing. It is unset on tag and merge
# request pipelines, which is the answer landed mode wants for both.
# Off CI it is the checked-out branch, or empty on a detached HEAD --
# also the wanted answer, since a detached HEAD is not main.
REF_NAME="${CI_COMMIT_BRANCH:-$(git symbolic-ref --quiet --short HEAD || true)}"

# Which of the three sources BASE_REF came from decides what an empty
# range means later, so the answer is recorded rather than collapsed
# into the value. `arg` and `ci` name a range somebody asked about;
# `merge-base` is this script guessing, and only the guess is allowed
# to fall back to tip mode.
BASE_REF="${1:-}"
BASE_SOURCE="arg"
if [[ -z "${BASE_REF}" ]]; then
    BASE_REF="${CI_MERGE_REQUEST_DIFF_BASE_SHA:-}"
    BASE_SOURCE="ci"
fi
if [[ -z "${BASE_REF}" ]]; then
    BASE_SOURCE="merge-base"
    # See "Landed mode" in the header: on a long-lived branch the
    # upstream is that branch's own remote ref, so an empty range means
    # "this push is all that is new" rather than "dev carries nothing
    # main does not". Everywhere else the question is what this branch
    # adds to main, which is what it has always been.
    UPSTREAM="origin/main"
    if is_landed_ref "${REF_NAME}"; then
        UPSTREAM="origin/${REF_NAME}"
    fi
    if ! BASE_REF="$(git merge-base "${UPSTREAM}" HEAD 2>/dev/null)"; then
        echo "error: could not derive BASE_REF (no arg, no CI var, no ${UPSTREAM})" >&2
        exit 2
    fi
fi

HEAD_REF="${2:-}"
if [[ -z "${HEAD_REF}" ]]; then
    # GitLab sets this in every MR pipeline context, but the variable
    # naming a commit and the clone having fetched it are separate
    # facts -- a shallow fetch can satisfy the first without the
    # second. Falling back to HEAD there keeps the old, over-wide
    # behaviour rather than failing the job.
    #
    # The `^{commit}` suffix is load-bearing. A bare
    # `git rev-parse --verify <40-hex>` succeeds on any syntactically
    # valid object name whether or not the object was fetched, so
    # without it an unfetched sha passes this guard and `git rev-list`
    # then dies on an invalid revision range, taking the script with it
    # under `set -e`. Peeling to ^{commit} is what makes the check
    # test existence rather than spelling.
    if [[ -n "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-}" ]] \
        && git rev-parse --verify "${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}^{commit}" >/dev/null 2>&1; then
        HEAD_REF="${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA}"
    else
        HEAD_REF="HEAD"
    fi
fi

if ! git rev-parse --verify "${BASE_REF}^{commit}" >/dev/null 2>&1; then
    echo "error: base ref '${BASE_REF}' does not resolve" >&2
    exit 2
fi
if ! git rev-parse --verify "${HEAD_REF}^{commit}" >/dev/null 2>&1; then
    echo "error: head ref '${HEAD_REF}' does not resolve" >&2
    exit 2
fi

# --- Select the commits to validate -----------------------------------------

# The commits a ref introduces on its own: the non-first parents of a
# merge commit, or the ref itself when it has none. One line of output
# per commit, the shape the range walk below already reads.
tip_commits() {
    local ref="$1" parents
    read -ra parents <<< "$(git log -1 --format=%P "${ref}")"
    if [[ "${#parents[@]}" -ge 2 ]]; then
        printf '%s\n' "${parents[@]:1}"
    else
        git rev-parse "${ref}"
    fi
}

# What the last push put on the branch. $CI_COMMIT_BEFORE_SHA is the
# tip the branch had beforehand, so the range is exactly the new
# commits -- the merge commit plus its squash commit for a merge, or
# every commit of a direct push, which taking only the tip would cut
# to one.
#
# GitLab sets that variable to all-zeros on a branch's first pipeline
# and in merge request pipelines, and a variable naming a commit is a
# separate fact from the clone having fetched it, so both are tested
# before the range is trusted. Off CI the variable does not exist at
# all. Every one of those falls back to tip_commits, as does a range
# that comes back empty (a force-push backwards, or an overridden
# HEAD_REF): this only runs on main, where checking the tip is always
# legitimate, just not always sufficient.
landed_commits() {
    local before="${CI_COMMIT_BEFORE_SHA:-}" range=""
    if [[ -n "${before}" && ! "${before}" =~ ^0+$ ]] \
        && git rev-parse --verify "${before}^{commit}" >/dev/null 2>&1; then
        range="$(git rev-list --reverse "${before}..${HEAD_REF}")"
    fi
    if [[ -n "${range}" ]]; then
        printf '%s\n' "${range}"
    else
        tip_commits "${HEAD_REF}"
    fi
}

commits="$(git rev-list --reverse "${BASE_REF}..${HEAD_REF}")"
landed_mode=0

if [[ -z "${commits}" ]]; then
    if [[ "${BASE_SOURCE}" != "merge-base" ]] || ! is_landed_ref "${REF_NAME}"; then
        echo "guard: no commits in ${BASE_REF}..${HEAD_REF}"
        exit 0
    fi
    landed_mode=1
    commits="$(landed_commits)"
    echo "guard: ${BASE_REF}..${HEAD_REF} is empty -- checking what the last push put on ${REF_NAME}"
fi

# --- Walk the range and validate each commit --------------------------------

checked=0
skipped=0
failed=0

while IFS= read -r sha; do
    [[ -z "${sha}" ]] && continue

    message="$(git log -1 --format=%B "${sha}")"
    subject="$(commit_subject <<< "${message}")"
    short="$(git rev-parse --short "${sha}")"

    if [[ -z "${subject}" ]]; then
        echo "FAIL ${short}: empty commit message" >&2
        failed=$((failed + 1))
        continue
    fi

    if is_merge_subject "${subject}"; then
        echo "skip ${short}: merge commit (${subject})"
        skipped=$((skipped + 1))
        continue
    fi

    checked=$((checked + 1))
    commit_ok=1

    if ! check_commit_subject "${subject}" 2> >(sed "s/^/  ${short}: /" >&2); then
        commit_ok=0
    fi
    if ! check_signed_off <<< "${message}" 2> >(sed "s/^/  ${short}: /" >&2); then
        commit_ok=0
    fi

    if [[ "${commit_ok}" -eq 1 ]]; then
        echo "pass ${short}: ${subject}"
    else
        echo "FAIL ${short}: ${subject}" >&2
        failed=$((failed + 1))
    fi
done <<< "${commits}"

echo ""
echo "guard: ${checked} checked, ${skipped} merge commit(s) skipped, ${failed} failed"

if [[ "${failed}" -gt 0 ]]; then
    # A landed-mode failure has no rebase waiting at the end of it: the
    # commit is already on main, usually as the squash commit of a
    # merge request whose title was edited after its last pipeline. Say
    # what the finding costs and what to do about it, rather than
    # leaving a reader to work out why the guard is reporting a commit
    # they cannot amend.
    #
    # OUTPUT=/dev/stdout on the preview: changelog-release defaults to
    # writing CHANGELOG.md, and a reader following this hint has
    # trouble enough without an unasked-for file at the end of it.
    if [[ "${landed_mode}" -eq 1 ]]; then
        if [[ "${failed}" -eq 1 ]]; then
            subject_phrase="This commit is"
        else
            subject_phrase="These ${failed} commits are"
        fi
        echo "" >&2
        echo "  ${subject_phrase} already on ${REF_NAME} and cannot be amended." >&2
        echo "  A subject that failed the grammar is dropped from the release" >&2
        echo "  notes too, by cliff.toml's filter_unconventional, and just as" >&2
        echo "  quietly: expect the gap in" >&2
        echo "  'make changelog-release VERSION=vX.Y.Z STRIP=all OUTPUT=/dev/stdout'" >&2
        echo "  and add the entry by hand on the GitLab Release page." >&2
    fi
    exit 1
fi

exit 0
