// Copyright (C) 2026 Postquant Labs Incorporated
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Compile-time parity check between the [`opcodes!`](crate::opcodes)
//! x-macro (the canonical Rust opcode table) and
//! `conformance/opcodes.yaml` (the canonical machine-readable table).
//!
//! The build script [`build.rs`](../../../build.rs) parses the YAML and
//! emits `YAML_OPCODES: &[(u8, &str, i8, &[(&str, u8)])]` into
//! `$OUT_DIR/opcodes_yaml.rs`. The `opcodes!` macro is invoked here with a
//! callback that constructs a parallel `MACRO_OPCODES` of the same shape.
//! A `const` assertion compares the two tables element-wise; any
//! disagreement fails the build.
//!
//! Four things are compared per opcode: the wire byte, the mnemonic, the
//! net stack effect, and the operand layout as `(name, byte width)` pairs.
//!
//! Two deliberate limits on that comparison:
//!
//! - **Net delta, not the pop/push pair.** The YAML declares `stack_pop`
//!   and `stack_push` separately (`SWAP` is `2 → 2`, `COPY` is `1 → 2`);
//!   the x-macro stores only `pushes − pops`, so the delta is the most the
//!   two tables can agree on. `SCLR` is the one opcode with no fixed
//!   delta: both sides spell it `i8::MIN`, from the YAML's `stack_reset`
//!   flag and the macro's sentinel respectively.
//! - **Operand name and width, not the declared kind.** The YAML's
//!   `register`/`label`/`immediate` kinds cannot be recovered from the
//!   Rust field types — a `u8` label and a [`Register`](crate::Register)
//!   are both one byte — so the operand *name* carries that distinction by
//!   convention, and the name is compared.
//!
//! Keeping the check in a `const` context means every `cargo build` (not
//! just `cargo test`) enforces parity — drift cannot land quietly.

/// One operand's comparable identity: declared name and encoded byte width.
type OperandRow = (&'static str, u8);

/// One opcode's comparable identity: wire byte, mnemonic, net stack
/// effect (`i8::MIN` for a reset), and operand layout.
type OpcodeRow = (u8, &'static str, i8, &'static [OperandRow]);

// Generated by build.rs. Defines `YAML_OPCODES: &[OpcodeRow]` using the
// aliases above.
include!(concat!(env!("OUT_DIR"), "/opcodes_yaml.rs"));

/// Narrow a type's size to the `u8` the opcode tables store.
///
/// Every operand in the table is at most eight bytes, so the cast is
/// lossless; the assertion holds the claim in place if that ever changes.
/// `u8::try_from` is not a `const fn`, so the check has to be written out.
#[expect(
    clippy::cast_possible_truncation,
    reason = "the assertion immediately above the cast bounds the value to u8::MAX"
)]
const fn operand_width(bytes: usize) -> u8 {
    assert!(
        bytes <= 255,
        "an opcode operand wider than 255 bytes cannot be compared against the YAML's `width`"
    );
    bytes as u8
}

/// Build a `(code, mnemonic, stack delta, operands)` slice from the
/// `opcodes!` macro expansion.
///
/// Operand widths come from [`size_of`] over each field's declared type,
/// which is exactly the encoded width for every type the table uses:
/// `u8`/[`Register`](crate::Register) are one byte, `u16` two, and a
/// `[u8; N]` immediate is `N`. That equivalence is an assumption about
/// layout, not a guarantee, so `widths_match_the_codec` below pins it to
/// what [`codec::encode`](crate::codec::encode) actually writes.
macro_rules! macro_opcodes_table {
    (
        $( ($code:literal, $variant:ident, $mnem:literal, $doc:literal, $delta:expr,
            {$($fname:ident: $fty:ty),* $(,)?}) ),*
        $(,)?
    ) => {
        const MACRO_OPCODES: &[OpcodeRow] = &[
            $( (
                $code,
                $mnem,
                $delta as i8,
                &[ $( (stringify!($fname), operand_width(size_of::<$fty>())), )* ],
            ), )*
        ];
    };
}

crate::opcodes!(macro_opcodes_table);

// `<[T]>::get` is not yet const-fn, so the bounded `while` loops below must
// index directly. Each access sits under an explicit `i < len` guard.
#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < ab.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn str_eq(a: &str, b: &str) -> bool {
    let ab = a.as_bytes();
    let bb = b.as_bytes();
    if ab.len() != bb.len() {
        return false;
    }
    let mut i = 0;
    while i < ab.len() {
        if ab[i] != bb[i] {
            return false;
        }
        i += 1;
    }
    true
}

#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < a.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn operands_match(a: &[(&str, u8)], b: &[(&str, u8)]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        let (an, aw) = a[i];
        let (bn, bw) = b[i];
        if aw != bw || !str_eq(an, bn) {
            return false;
        }
        i += 1;
    }
    true
}

#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < MACRO_OPCODES.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn tables_match() -> bool {
    if MACRO_OPCODES.len() != YAML_OPCODES.len() {
        return false;
    }
    let mut i = 0;
    while i < MACRO_OPCODES.len() {
        let (mc, mn, md, mo) = MACRO_OPCODES[i];
        let (yc, yn, yd, yo) = YAML_OPCODES[i];
        if mc != yc || md != yd || !str_eq(mn, yn) || !operands_match(mo, yo) {
            return false;
        }
        i += 1;
    }
    true
}

// No row or column can be named here: a `const` panic message has to be a
// literal, and the failing build stops the unit tests below from running.
const _: () = assert!(
    tables_match(),
    "opcodes! x-macro disagrees with conformance/opcodes.yaml — some row's \
     wire byte, mnemonic, net stack effect, or operand (name, width) list \
     differs. Compare xqvm/src/bytecode/types/table.rs against \
     conformance/opcodes.yaml by hand: `make opcode-parity` will not narrow \
     it down, because its Rust half is this same assertion and its Python \
     half compares operand types rather than names and does not see \
     `stack_reset` at all."
);

#[cfg(test)]
mod tests {
    #[test]
    fn tables_have_expected_size() {
        assert_eq!(super::MACRO_OPCODES.len(), 93);
        assert_eq!(super::YAML_OPCODES.len(), 93);
    }

    #[test]
    fn tables_agree() {
        assert_eq!(super::MACRO_OPCODES, super::YAML_OPCODES);
    }

    /// `tables_agree` catches the two sides disagreeing. These pin what
    /// the compared columns *mean*, so a change that makes both sides
    /// equally wrong still fails.
    fn row(mnemonic: &str) -> super::OpcodeRow {
        *super::MACRO_OPCODES
            .iter()
            .find(|(_, m, _, _)| *m == mnemonic)
            .unwrap_or_else(|| panic!("no opcode {mnemonic} in the table"))
    }

    #[test]
    fn sclr_is_the_only_reset() {
        let resets: Vec<&str> = super::MACRO_OPCODES
            .iter()
            .filter(|(_, _, delta, _)| *delta == i8::MIN)
            .map(|(_, mnemonic, _, _)| *mnemonic)
            .collect();
        assert_eq!(resets, ["SCLR"]);
    }

    #[test]
    fn stack_deltas_are_net_effects() {
        // ADD pops two and pushes one; COPY pushes a duplicate; SWAP
        // reorders without changing depth.
        assert_eq!(row("ADD").2, -1);
        assert_eq!(row("COPY").2, 1);
        assert_eq!(row("SWAP").2, 0);
    }

    #[test]
    fn operand_widths_are_encoded_byte_counts() {
        assert_eq!(row("PUSH8").3, [("val", 8)]);
        assert_eq!(row("PUSH1").3, [("val", 1)]);
        // A u16 label is two bytes; the narrow form's u8 label is one.
        assert_eq!(row("JUMP2").3, [("label", 2)]);
        assert_eq!(row("JUMP1").3, [("label", 1)]);
        // A register is one byte, and a no-operand opcode has none.
        assert_eq!(row("LOAD").3, [("reg", 1)]);
        assert_eq!(row("TARGET").3, []);
    }

    #[test]
    fn multi_operand_opcodes_keep_operand_order() {
        assert_eq!(row("ENERGY").3, [("model", 1), ("sample", 1)]);
    }

    macro_rules! default_instructions {
        (
            $( ($code:literal, $variant:ident, $mnem:literal, $doc:literal, $delta:expr,
                {$($fname:ident: $fty:ty),* $(,)?}) ),*
            $(,)?
        ) => {
            &[ $( (
                $mnem,
                crate::Instruction::$variant { $($fname: <$fty as Default>::default(),)* },
            ) ),* ]
        };
    }

    /// The compared widths are `size_of` over each operand's declared
    /// type. That is only the encoded width as long as no field type
    /// carries padding or a niche-optimised layout, which `size_of`
    /// cannot tell us. Encode every opcode and hold the sum of its
    /// declared widths to the bytes the codec writes after the opcode
    /// byte, so the assumption fails here rather than silently agreeing
    /// with a YAML row the wire format has outgrown.
    #[test]
    fn widths_match_the_codec() {
        let instructions: &[(&str, crate::Instruction)] = crate::opcodes!(default_instructions);
        for (mnemonic, instr) in instructions {
            let declared: usize = row(mnemonic).3.iter().map(|(_, w)| usize::from(*w)).sum();
            let bytes = crate::codec::encode(instr);
            let encoded = bytes
                .len()
                .checked_sub(1)
                .expect("every encoding starts with the opcode byte");
            assert_eq!(
                declared, encoded,
                "{mnemonic}: operands declared as {declared} bytes, codec writes {encoded}"
            );
        }
    }
}
