// Copyright (C) 2026 Postquant Labs Incorporated
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// SPDX-License-Identifier: AGPL-3.0-or-later

//! Compile-time parity check between the [`opcodes!`](crate::opcodes)
//! x-macro (the canonical Rust opcode table) and
//! `xqvm/opcodes.yaml` (the canonical machine-readable table).
//!
//! The build script [`build.rs`](../../../build.rs) parses the YAML and
//! emits `YAML_OPCODES: &[(u8, &str, StackEffect, &[(&str, u8)])]` into
//! `$OUT_DIR/opcodes_yaml.rs`. The `opcodes!` macro is invoked here with a
//! callback that constructs a parallel `MACRO_OPCODES` of the same shape.
//! A `const` assertion compares the two tables element-wise; any
//! disagreement fails the build.
//!
//! Four things are compared per opcode: the wire byte, the mnemonic, the
//! stack effect, and the operand layout as `(name, byte width)` pairs.
//!
//! The stack effect is compared as a pop count and a push count, not as
//! their difference: `SWAP` (`2 -> 2`) and a hypothetical `0 -> 0` have the
//! same net effect and still disagree here. `SCLR` is the one opcode with
//! no fixed count; both sides spell it [`StackEffect::Reset`], from the
//! YAML's `stack_reset` flag and the macro's own row respectively.
//!
//! One deliberate limit on the comparison: **operand name and width, not
//! the declared kind.** The YAML's `register`/`label`/`immediate` kinds
//! cannot be recovered from the Rust field types -- a `u8` label and a
//! [`Register`](crate::Register) are both one byte -- so the operand
//! *name* carries that distinction by convention, and the name is compared.
//!
//! Keeping the check in a `const` context means every `cargo build` (not
//! just `cargo test`) enforces parity — drift cannot land quietly.

use crate::StackEffect;

/// One operand's comparable identity: declared name and encoded byte width.
type OperandRow = (&'static str, u8);

/// One opcode's comparable identity: wire byte, mnemonic, stack effect,
/// and operand layout.
type OpcodeRow = (u8, &'static str, StackEffect, &'static [OperandRow]);

// Generated by build.rs. Defines `YAML_OPCODES: &[OpcodeRow]` using the
// aliases above.
include!(concat!(env!("OUT_DIR"), "/opcodes_yaml.rs"));

/// Narrow a type's size to the `u8` the opcode tables store.
///
/// Every operand in the table is at most eight bytes, so the cast is
/// lossless; the assertion holds the claim in place if that ever changes.
/// `u8::try_from` is not a `const fn`, so the check has to be written out.
#[expect(
    clippy::cast_possible_truncation,
    reason = "the assertion immediately above the cast bounds the value to u8::MAX"
)]
const fn operand_width(bytes: usize) -> u8 {
    assert!(
        bytes <= 255,
        "an opcode operand wider than 255 bytes cannot be compared against the YAML's `width`"
    );
    bytes as u8
}

/// Build a `(code, mnemonic, stack effect, operands)` slice from the
/// `opcodes!` macro expansion.
///
/// Operand widths come from [`size_of`] over each field's declared type,
/// which is exactly the encoded width for every type the table uses:
/// `u8`/[`Register`](crate::Register) are one byte, `u16` two, and a
/// `[u8; N]` immediate is `N`. That equivalence is an assumption about
/// layout, not a guarantee, so `widths_match_the_codec` below pins it to
/// what [`codec::encode`](crate::codec::encode) actually writes.
macro_rules! macro_opcodes_table {
    (
        $( ($code:literal, $variant:ident, $mnem:literal, $doc:literal, $stack:expr,
            {$($fname:ident: $fty:ty),* $(,)?}) ),*
        $(,)?
    ) => {
        const MACRO_OPCODES: &[OpcodeRow] = &[
            $( (
                $code,
                $mnem,
                $stack,
                &[ $( (stringify!($fname), operand_width(size_of::<$fty>())), )* ],
            ), )*
        ];
    };
}

crate::opcodes!(macro_opcodes_table);

// `<[T]>::get` is not yet const-fn, so the bounded `while` loops below must
// index directly. Each access sits under an explicit `i < len` guard.
#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < ab.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn str_eq(a: &str, b: &str) -> bool {
    let ab = a.as_bytes();
    let bb = b.as_bytes();
    if ab.len() != bb.len() {
        return false;
    }
    let mut i = 0;
    while i < ab.len() {
        if ab[i] != bb[i] {
            return false;
        }
        i += 1;
    }
    true
}

#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < a.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn operands_match(a: &[(&str, u8)], b: &[(&str, u8)]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        let (an, aw) = a[i];
        let (bn, bw) = b[i];
        if aw != bw || !str_eq(an, bn) {
            return false;
        }
        i += 1;
    }
    true
}

/// `StackEffect`'s derived `PartialEq` is not `const`, so the comparison
/// is written out: pops against pops, pushes against pushes.
const fn effects_match(a: StackEffect, b: StackEffect) -> bool {
    match (a, b) {
        (StackEffect::Reset, StackEffect::Reset) => true,
        (
            StackEffect::Fixed {
                pops: a_pops,
                pushes: a_pushes,
            },
            StackEffect::Fixed {
                pops: b_pops,
                pushes: b_pushes,
            },
        ) => a_pops == b_pops && a_pushes == b_pushes,
        _ => false,
    }
}

#[expect(
    clippy::indexing_slicing,
    reason = "const fn cannot use slice::get; loop condition bounds the index"
)]
#[expect(
    clippy::arithmetic_side_effects,
    reason = "the `while i < a.len()` condition bounds the cursor; const fn cannot use checked_add"
)]
const fn tables_match(a: &[OpcodeRow], b: &[OpcodeRow]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut i = 0;
    while i < a.len() {
        let (ac, an, ae, ao) = a[i];
        let (bc, bn, be, bo) = b[i];
        if ac != bc || !effects_match(ae, be) || !str_eq(an, bn) || !operands_match(ao, bo) {
            return false;
        }
        i += 1;
    }
    true
}

// No row or column can be named here: a `const` panic message has to be a
// literal, and the failing build stops the unit tests below from running.
const _: () = assert!(
    tables_match(MACRO_OPCODES, YAML_OPCODES),
    "opcodes! x-macro disagrees with xqvm/opcodes.yaml -- some row's \
     wire byte, mnemonic, stack effect (pops, pushes or reset), or operand \
     (name, width) list differs. Compare xqvm/src/bytecode/types/table.rs \
     against xqvm/opcodes.yaml by hand: `make opcode-parity` will not \
     narrow it down, because its Rust half is this same assertion and its \
     Python half compares operand types rather than names and does not see \
     `stack_reset` at all."
);

#[cfg(test)]
mod tests {
    use crate::StackEffect;

    #[test]
    fn tables_have_expected_size() {
        assert_eq!(super::MACRO_OPCODES.len(), 93);
        assert_eq!(super::YAML_OPCODES.len(), 93);
    }

    #[test]
    fn tables_agree() {
        assert_eq!(super::MACRO_OPCODES, super::YAML_OPCODES);
    }

    /// `tables_agree` catches the two sides disagreeing. These pin what
    /// the compared columns *mean*, so a change that makes both sides
    /// equally wrong still fails.
    fn row(mnemonic: &str) -> super::OpcodeRow {
        *super::MACRO_OPCODES
            .iter()
            .find(|(_, m, _, _)| *m == mnemonic)
            .unwrap_or_else(|| panic!("no opcode {mnemonic} in the table"))
    }

    #[test]
    fn sclr_is_the_only_reset() {
        let resets: Vec<&str> = super::MACRO_OPCODES
            .iter()
            .filter(|(_, _, effect, _)| *effect == StackEffect::Reset)
            .map(|(_, mnemonic, _, _)| *mnemonic)
            .collect();
        assert_eq!(resets, ["SCLR"]);
    }

    #[test]
    fn stack_effects_are_pop_push_pairs() {
        // ADD pops two and pushes one; COPY pops one and pushes it back
        // with its duplicate; SWAP pops two and pushes them reordered.
        assert_eq!(row("ADD").2, StackEffect::fixed(2, 1));
        assert_eq!(row("COPY").2, StackEffect::fixed(1, 2));
        assert_eq!(row("SWAP").2, StackEffect::fixed(2, 2));
    }

    /// The `const` assertion can only be seen failing by breaking the
    /// build, so run its comparison here against a copy of the table
    /// whose one change keeps the net effect: `SWAP` as `0 -> 0` instead
    /// of `2 -> 2`. A check that compared net deltas would pass it.
    #[test]
    fn a_pop_push_mismatch_with_the_same_net_effect_is_rejected() {
        let mut altered = super::YAML_OPCODES.to_vec();
        let swap = altered
            .iter_mut()
            .find(|(_, m, _, _)| *m == "SWAP")
            .expect("SWAP is in the table");
        swap.2 = StackEffect::fixed(0, 0);
        assert!(super::tables_match(
            super::MACRO_OPCODES,
            super::YAML_OPCODES
        ));
        assert!(!super::tables_match(super::MACRO_OPCODES, &altered));
    }

    #[test]
    fn a_reset_is_not_a_fixed_effect() {
        assert!(!super::effects_match(
            StackEffect::Reset,
            StackEffect::fixed(0, 0)
        ));
    }

    #[test]
    fn operand_widths_are_encoded_byte_counts() {
        assert_eq!(row("PUSH8").3, [("val", 8)]);
        assert_eq!(row("PUSH1").3, [("val", 1)]);
        // A u16 label is two bytes; the narrow form's u8 label is one.
        assert_eq!(row("JUMP2").3, [("label", 2)]);
        assert_eq!(row("JUMP1").3, [("label", 1)]);
        // A register is one byte, and a no-operand opcode has none.
        assert_eq!(row("LOAD").3, [("reg", 1)]);
        assert_eq!(row("TARGET").3, []);
    }

    #[test]
    fn multi_operand_opcodes_keep_operand_order() {
        assert_eq!(row("ENERGY").3, [("model", 1), ("sample", 1)]);
    }

    macro_rules! default_instructions {
        (
            $( ($code:literal, $variant:ident, $mnem:literal, $doc:literal, $_stack:expr,
                {$($fname:ident: $fty:ty),* $(,)?}) ),*
            $(,)?
        ) => {
            &[ $( (
                $mnem,
                crate::Instruction::$variant { $($fname: <$fty as Default>::default(),)* },
            ) ),* ]
        };
    }

    /// The compared widths are `size_of` over each operand's declared
    /// type. That is only the encoded width as long as no field type
    /// carries padding or a niche-optimised layout, which `size_of`
    /// cannot tell us. Encode every opcode and hold the sum of its
    /// declared widths to the bytes the codec writes after the opcode
    /// byte, so the assumption fails here rather than silently agreeing
    /// with a YAML row the wire format has outgrown.
    #[test]
    fn widths_match_the_codec() {
        let instructions: &[(&str, crate::Instruction)] = crate::opcodes!(default_instructions);
        for (mnemonic, instr) in instructions {
            let declared: usize = row(mnemonic).3.iter().map(|(_, w)| usize::from(*w)).sum();
            let bytes = crate::codec::encode(instr);
            let encoded = bytes
                .len()
                .checked_sub(1)
                .expect("every encoding starts with the opcode byte");
            assert_eq!(
                declared, encoded,
                "{mnemonic}: operands declared as {declared} bytes, codec writes {encoded}"
            );
        }
    }
}
